name: Test build for golang
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Chceckout Code
              uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.23'
            - name: display the installed version
              run: go version 
            - name: install the required dependencies
              run: go mod download
            